version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "5000:8080"
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/webspidersoundtrack
      PORT: 8080
      NODE_ENV: development

  postgres:
    image: postgres:11.3
    ports:
      - "35432:5432"
    # volumes:
    #   - ./init-db.js:/usr/src/app/init-db.js
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: webspidersoundtrack
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: